name: Deploy Blog

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: npm install
        
    - name: Build
      run: npm run build
<<<<<<< HEAD
      env:
        VITE_LAMBDA_URL: ${{ secrets.VITE_LAMBDA_URL }}
=======
>>>>>>> 9ec1b104371c41769483828d78c99e89384c8627
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Deploy to S3
<<<<<<< HEAD
      run: aws s3 sync dist/ s3://blog.mujakayadan.com --delete
=======
      run: aws s3 sync out/ s3://blog.mujakayadan.com --delete 
>>>>>>> 9ec1b104371c41769483828d78c99e89384c8627
        
    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.BLOG_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"